---
##############
# CONFIG.YML #
##############
# AUTHOR: Ibenrm01

# LANGUAGE
# tags: {emote_name}
use.emotes: "§aYou use §d{emote_name} §aEmotes!"
# tags: {emote_name}
#       {uid}
create.emote-success: "§aSuccessfully created §d{emote_name} §7/ §d{uid} §7/ §d{permission} §aEmotes!"
create.emote-already: "§cAlready created §d{emote_name} §aEmotes!"
# tags: {emote_name}
remove.emote-success: "§aSuccessfully removed §d{emote_name} §7/ §d{permission} §aEmotes!"
remove.emote-already: "§aAlready removed §d{emote_name} §aEmotes!"
# tags: not have
exit.menu: "§aThanks for open menu!"

# FORMS(UI)
forms.create:
  title: "§l§eCREATED EMOTES!"
  content: "§6Edit config.yml!"
...